// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhseBLNh8RRDhtu9RmlnLLbW_o0A1a-o',
    appId: '1:178920984242:web:8e2ab8bbceb266574783ab',
    messagingSenderId: '178920984242',
    projectId: 'child-safety-app-b463c',
    authDomain: 'child-safety-app-b463c.firebaseapp.com',
    storageBucket: 'child-safety-app-b463c.firebasestorage.app',
    measurementId: 'G-2X6WMP8LRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlmnnfva0jNYNgV9Hizx8Ozbsdc19Le4',
    appId: '1:178920984242:android:1cb33a49003b02454783ab',
    messagingSenderId: '178920984242',
    projectId: 'child-safety-app-b463c',
    storageBucket: 'child-safety-app-b463c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqwzokG62vbG-2uMwmlTOsQeRleAfxftw',
    appId: '1:178920984242:ios:ebefb04ef77521af4783ab',
    messagingSenderId: '178920984242',
    projectId: 'child-safety-app-b463c',
    storageBucket: 'child-safety-app-b463c.firebasestorage.app',
    iosClientId: '178920984242-qtp42rovla7rgbdcvp9hr9elcnugbukq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqwzokG62vbG-2uMwmlTOsQeRleAfxftw',
    appId: '1:178920984242:ios:ebefb04ef77521af4783ab',
    messagingSenderId: '178920984242',
    projectId: 'child-safety-app-b463c',
    storageBucket: 'child-safety-app-b463c.firebasestorage.app',
    iosClientId: '178920984242-qtp42rovla7rgbdcvp9hr9elcnugbukq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMhseBLNh8RRDhtu9RmlnLLbW_o0A1a-o',
    appId: '1:178920984242:web:e143b762ff848d6e4783ab',
    messagingSenderId: '178920984242',
    projectId: 'child-safety-app-b463c',
    authDomain: 'child-safety-app-b463c.firebaseapp.com',
    storageBucket: 'child-safety-app-b463c.firebasestorage.app',
    measurementId: 'G-S2KW4J00FY',
  );

}